LICENSE
The file https://svn.astron.nl/LOFAR/trunk/COPYING applies to PyBDSM as well, so we should include this license.
=> Add LICENSE (copy from LOVAR svn)

bdsf/gausfit.py
If for some reason Gaussian parameters end up being NaN, best thing is to flag the result -- also prevents the code crashing when it tries to convert NaN to integer.
=> Fix crash if Gaussian parameters are NaN

setup.py
Checking for some basic dependencies. We could add checking for more complicated dependencies (like `fits` from either casacore or astropy) later.
=> Check for dependencies at setup time

bdsf/pybdsf
Adding a shebang will make starting the command line tool as easy as typing `pybdsf` (no `python` in front of it).
=> Add shebang to command line tool

bdsf/gaul2srl.py
The low peak fluxes cause very large errors in RA and Dec, as reported in issue #31.
=> Fix very low centroid peak fluxes

setup.py
Adds a separate command for building the static fortran libs and call it as part of "build_ext", does something similar for "clean". This addresses lofar-astron/PyBDSF/issues/45
=> change how setup.py builds the static libs

bdsf/output.py
Small hack to implement issue https://github.com/lofar-astron/PyBDSF/issues/52. In order not to break any keyword, the image keyword in the catalog header is `I_CTYPE1` instead of `CTYPE1` etc
=> Appended image FITS header into catalog FITS header

src/c++/MGFunction1.cc, src/c++/MGFunction2.cc
Compiling on arch linux with boost 1.67 and gcc 8.1.1 I got a compilation error because of a namespace collision on `list`, solved by removing `using namespace std`.
=> Fix name collision of std::list and boost::python::list

setup.py, src/c++/cbdsm_main.cc
The hanging described in issue #63 seems to be caused by a segfault due to numpy not being initialized. This PR fixes it on my test system.
=> Initialize numpy to avoid segfault in Gaussian fitting (issue #63)

README.rst
I faced installation issues for PyBDSF on Ubuntu 16.04 in environment without conda. After some lookup, I realized the errors being due to compiler version difference for gcc, g++ (6.5 both) and gfortran(5.5). After using update-alternatives and changing gcc, g++ version to 5.5 (same as gfortran), the installation worked without any issue. I've created a gist for 'update-alternatives' usage [here](https://gist.github.com/kiryteo/e7cb52ecce8c2b25eca6acdd8ddbb5a7).
=> Installation without using conda (Readme update)

.travis.yml, bdsf/shapelets.py
As suggested by Tammo Jan, changing to Python 3.5 fixed the boost-python issue that occurred with 3.4. 
I also fixed the import of scipy's factorial function.
=> Fix Travis-CI issue with Python 3

.travis.yml
Travis shows intermittent segfaults on the test `tbdsf_process_images`.
I cannot reproduce this segfault on any other machine, not even a docker
with ubuntu 16.04 and python 3.5, same as travis. So I suggest to ignore
it for now.
=> Allow failing test on python 3.5

natgrid/Src/natgridmodule.c
The function PyArray_FromDimsAndData was deprecated in recent numpy
versions. Replace it by the alternative PyArray_NewFromDescr. Inspired
by the old code in https://github.com/numpy/numpy/pull/14100/files
=> Use PyArray_NewFromDescr in natgrid

setup.py, test/tbdsf_process_image.py
If boost is installed in a non-standard location, but boost headers are available in a system dir (e.g. `/usr/include`) building may work, but at runtime a symbol may not be found. This commit guesses the include directory from the found boost library, and passes that include directory to the build process.
We should really move away from boost_python...
=> Fix boost include dirs

setup.py
solves an issue of PyBDSF not being able to find boost library when using Python3, since boost_python can have a few name variations and these are hard coded into the setup.py file.
=> add boost_python3 and numpy_python3 to libnames in find functions

setup.py
The directory `/usr/lib/x86_64-linux-gnu` is obviously very architecture specific. However, `sys.implementation` offers a corresponding variable `_multiarch`, which is used here instead. See also https://wiki.debian.org/Python/MultiArch 
After applying this, PyBDSF [compiles on all out platforms](https://buildd.debian.org/status/logs.php?pkg=pybdsf&ver=1.9.2-2&suite=sid) (MIPS still pending):
=> Use system specific multiarch name instead of x86_64

bdsf/wavelet_atrous.py
wavelet_atrous.py appears to use a flag 'has_pyfftw' to check if the module pyfftw.interfaces could be imported, but this flag is never set, leading to a NameError as follows: https://pastebin.com/Wz7nwnH3.
Setting it True/False in the try/except block where pyfftw.interfaces is attempted to be imported should address it.
Python: 3.8.6
PyBDSF: 1.9.2
=> has_pyfftw used, but not defined in wavelet_atrous.py

pyproject.toml
As discussed. Makes build system compliant with PEP 517
=> Fixes #148

manylinux2010/build.sh, manylinux2010/wheel38.docker, manylinux2010/wheel39.docker
Added support for building binary wheels for Python 3.8 and 3.9. Removed support for Python 2.7, 3.4 and 3.5, because these version are obsolete and no longer supported by `manylinux2010`.
=> Build binary wheels for Python 3.8 and 3.9

bdsf/functions.py, bdsf/wavelet_atrous.py
This PR provides a replacement for the private `_centered()` function from scipy that is no longer available (see issue #171). It also updates the `fft()` and `ifft()` calls used by the PSF variation module.
=> Replace private scipy function

bdsf/gausfit.py, bdsf/opts.py, bdsf/spectralindex.py, doc/source/process_image.rst
This PR improves the handling of the beam when the beam_spectrum option is set to None by searching the header for the beam sizes or by scaling the size with frequency. Previously, no scaling was done.
=> Improve handling of beam in spectral index module

bdsf/rmsimage.py
np.alen() has been removed from NumPy v1.23.
see https://numpy.org/doc/stable/release/1.23.0-notes.html?highlight=alen#expired-deprecations
=> Use len() instead of np.alen().

manylinux2010/build.sh, manylinux2010/wheel310.docker
And bump Boost version to fix removal of deprecated function: https://github.com/boostorg/python/pull/344
I've only bumped the Boost version in the Python 3.10 build, one question would be whether that should be updated for all build wheels.
=> Add binary wheels for Python 3.10

pyproject.toml
Most recent changes to `setuptools` break compatibility with `numpy.distutils`, resulting in the following error:
```
ImportError: cannot import name 'Log' from 'distutils.log' (/tmp/pip-build-env-ewbr2q8n/overlay/lib/python3.8/site-packages/setuptools/_distutils/log.py)
```
See https://github.com/numpy/numpy/issues/22623 for more details.
This commit fixes issue #189.
=> Fix ImportError in setuptools

manylinux2014/build.sh, manylinux2014/py_wheel.docker, pyproject.toml, setup.py, src/fortran/pytess_roundness.f, src/fortran/pytess_simple.f
The Python 3.11 build failed, due to some obscure error generated by `f2py`. 
Further investigation showed that the problem is caused by a bug in `f2py.crackfortran`: see https://github.com/numpy/numpy/issues/23533 (BUG: f2py.crackfortran fails on comment after endif statement). The quick work-around was to fix the affected Fortran files.
After that fix, it turned out that the self test failed. This could be tracked down to a problem with Boost and Python 3.11: see https://github.com/boostorg/python/issues/400 (Python 3.11 gives SystemError: type Boost.Python.enum has the Py_TPFLAGS_HAVE_GC flag but has no traverse function). Bumping the Boost version to 1.81 resolved this issue.
Fixes #189
=> Fix build issue with Python 3.11

bdsf/functions.py, bdsf/gausfit.py, bdsf/opts.py, bdsf/readimage.py, doc/source/algorithms.rst, doc/source/process_image.rst
This PR fixes a number of issues with error estimation, including an incorrect treatment of the errors when correcting for projection effects and when the `fix_to_beam` option is enabled.
=> Fix issues with error estimation

bdsf/make_residimage.py, bdsf/opts.py, doc/source/process_image.rst
This PR fixes issue #212 and adds a new option to `process_image` (called `savefits_modelim`) to save the Gaussian model image as well.
=> Fix saving of residual image and add option to save model image

bdsf/functions.py, bdsf/output.py, bdsf/psf_vary.py, bdsf/pybdsf.py, setup.py
Python 3.12 no longer ships with `distutils`. Replaced the use of `distutils.version` with `packaging.version`.
=> Replace distutils for Python 3.12

bdsf/collapse.py, bdsf/psf_vary.py, bdsf/shapefit.py, doc/source/process_image.rst
This PR fixes an issue described in #218, where the value of the `frequency_sp` option was ignored during the collapse of the image channels.
=> Fix issue with frequency_sp being ignored

.readthedocs.yaml, doc/requirements.txt
ReadtheDocs nowadays requires the presence of a `.readthedocs.yaml` configuration file in the root directory of the repository. Added one, based on the template provided by ReadtheDocs.
=> Fix ReadtheDocs

pyproject.toml
Due to incompatibilities with NumPy 2.0, we need to restrict NumPy version to < 2.
=> Set upper limit on NumPy version

bdsf/_changelog.py, doc/source/whats_new.rst
Updated Change Log and What's New
=> Update changelog and whats_new

bdsf/functions.py
Sort the array first, then reuse for both median calculation and finding the clipped subset
=> Improve performance of iterative sigma clipped rms

bdsf/rmsimage.py
The map_coordinates step is quite computationally intensive in the SKA usecase. It is not amenable to multiprocessing based parallelisation because the ratio of output to computation is quite high, but seems to work very well with threading. 
There is some axis gymnastics (which maybe the "indexing" parameter to meshgrid could help with) which I've tried to follow, but please do check.
=> Parellelise map_coordinates with multithreading
